version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 300
      runas: root

  BeforeInstall:
    - location: scripts/empty.sh
      timeout: 60
      runas: root

  Install:
    - location: scripts/empty.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/empty.sh
      timeout: 60
      runas: root

  ValidateService:
    - location: scripts/empty.sh
      timeout: 60
      runas: root

